django-web/mysite/myapp/urls.py
# is used to handle all coming urls

"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path
from myapp import views

app_name = 'myapp'
urlpatterns = [
    path('book/', views.book, name='book'),
    path('add_book/', views.add_book, name='add_book'),
    path('book/<int:book_id>', views.detail, name='detail'),
    path('update/<int:id>', views.update, name='update'),
    path('delete/<int:id>', views.delete, name='delete'),
]

django-web/mysite/mysite/urls.py
# is used to handle all coming urls

"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

django-web/mysite/myapp/models.py
# define structure wand blue print of my data base table
from django.db import models


# Create your models here.
class Book(models.Model):
    def __str__(self):
        return self.name

    name = models.CharField(max_length=100)
    desc = models.CharField(max_length=500)
    price = models.IntegerField()
    image = models.ImageField(default='default.jpg', upload_to='book_images/')

django-web/mysite/myapp/forms.py
from django import forms
from .models import Book


class BookForm(forms.ModelForm):
    # meta class which holds information about class itself
    class Meta:
        model = Book
        fields = ['name', 'desc', 'price', 'image']

django-web/mysite/myapp/views.py
# control what do I want to view on my web page
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import Book
from .forms import BookForm


# Create your views here.
def index(request):
    return HttpResponse("Hello World")


def homepage(request):
    return render(request, 'myapp/index.html')


def book(request):
    book_list = Book.objects.all()
    context = {
        'book_list': book_list
    }
    return render(request, 'myapp/books.html', context)


def detail(request, book_id):
    book = Book.objects.get(id=book_id)
    return render(request, 'myapp/book.html', {
        'book': book
    })


def update(request, id):
    book = Book.objects.get(id=id)
    form = BookForm(request.POST or None, request.FILES, instance=book)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'myapp/edit.html', {'form': form, 'book': book})


def add_book(request):
    if request.method == "POST":
        name = request.POST.get('name', )
        desc = request.POST.get('desc', )
        price = request.POST.get('price', )
        image = request.FILES['image']
        book = Book(name=name, desc=desc, price=price, image=image)
        book.save()
    return render(request, 'myapp/add_book.html')


def delete(request, id):
    if request.method == "POST":
        book = Book.objects.get(id=id)
        book.delete()
        return redirect('/')
    return render(request, 'myapp/delete.html')

django-web/mysite/myapp/templates/myapp/add_book.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" id="name" placeholder="Enter book name">
    <input type="text" name="desc" id="desc" placeholder="Enter book description">
    <input type="text" name="price" id="price" placeholder="Enter book price">
    <input type="file" name="image" id="image">
    <input type="submit" name="" id="">
</form>

django-web/mysite/myapp/templates/myapp/book-base-header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'myapp/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Books</title>
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <h1 class="navbar-brand">Book Store</h1>
</nav>
<br/>
{% block body %}
{% endblock %}
</body>
</html>

django-web/mysite/myapp/templates/myapp/book.html
{% extends 'myapp/book-base-header.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img width="300" height="300" src="{{book.image.url}}">

        </div>
        <div class="col-md-6">
            <h2>{{book.name}} </h2>

            <h4>{{book.desc}}</h4>

            <h6>{{book.price}}</h6>

            <a class="btn btn-warning" href="{% url 'myapp:update' book.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'myapp:delete' book.id %}">Delete</a>

        </div>
    </div>
</div>
{% endblock %}

django-web/mysite/myapp/templates/myapp/books.html
{% extends 'myapp/book-base-header.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for book in book_list %}
        <div class="col-md-3">
            <div class="card">
                <img src="{{book.image.url}}" class="card-img-top" alt="">
                <div class="card-body">
                    <h5 class="card-title">{{book.name}}</h5>
                    <p class="card-text">${{book.price}}</p>
                    <a class="btn btn-warning" href="{% url 'myapp:detail' book.id %}">View Details </a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

django-web/mysite/myapp/templates/myapp/delete.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    Are you sure you want to delete this book?
    <input type="submit" name="" id="">
</form>

django-web/mysite/myapp/templates/myapp/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="" id="">
</form>

django-web/mysite/myapp/templates/myapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> Hello From Django</h1>

<button type="button"><a href="/admin">Admin</a></button>

<button type="button"><a href="/index">Index</a></button>

<button type="button"><a href="/book">Book</a></button>

<button type="button"><a href="/add_book">Add Book</a></button>

</body>

</html>